[package]
name = "aion-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
# aion-event = { path = "../aion-event" }
aion-state = { path = "../aion-state" }
aion-program = { path = "../aion-program" }
aion-system = { path = "../aion-system" }


execution-graph = { path = "../execution_graph" }


tokio = { version = "1.52.1", features = [ "rt", "rt-multi-thread" ] }
threadpool = "1.8.1"