[package]
name = "aion-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
aion-program = { path = "../aion-program" }
aion-system = { path = "../aion-system" }
aion-ecs = { path = "../aion-ecs" }
execution-graph = { path = "../execution_graph" }

hecs = "0.11.0"
tokio = { version = "1.52.1", features = [ "rt-multi-thread", "sync" ] }
parking_lot = { version = "0.12.5", features = ["arc_lock"] }
rayon = "1.12.0"
futures = "0.3.32"